### ISSUE TITLE
사이트 전반에 적용된 word-break 속성 점검

### ISSUE THREAD

**Issue by paikwiki** [paikwiki/paikwiki.github.io#3]
중점적으로 체크해야할 부분.

[번역 - 해커처럼 블로깅하기](http://paikwiki.github.io/2018/10/blogging-like-a-hacker-kr)의 아래 문장:

> 이 포스트의 URL은 http://tom.preston-werner.com/2008/11/17/blogging-like-a-hacker.html입니다.

[젬 기반의 지킬 테마 적용하기](http://paikwiki.github.io/2018/04/gem-based-theme-for-jekyll)의 아래 문장:

> 예제 포스트: http://127.0.0.1:4000/jekyll/update/{YYYY}/{MM}/{DD}/welcome-to-jekyll

`_sass/basic.scss`의 58-62라인의 `word-break: keep-all;`을 취소하고 전반적으로 문장을 처리하는 부분을 손봐야 함.

````scss
// _sass/basic.scss:58-62 
p, span, a, li {
  line-height: 1.8;
  word-break: keep-all;
  vertical-align: baseline;
}
````
